dist: trusty

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script: mvn test -B

after_success:
  - mvn clean
  - curl $TRYGGVE_CA --create-dirs -o ~/.docker/ca.pem
  - curl $TRYGGVE_CERT --create-dirs -o ~/.docker/cert.pem
  - curl $TRYGGVE_KEY --create-dirs -o ~/.docker/key.pem
  - curl $CA_CERT_URL -o CA.cert
  - curl $CA_KEY_URL -o CA.key
  - openssl req -nodes -newkey rsa:2048 -keyout client.key -out CSR.csr -subj "/C=NO/ST=Oslo/L=Oslo/O=UiO/OU=IFI/CN=support@localega.com"
  - openssl x509 -req -in CSR.csr -CA CA.cert -CAkey CA.key -set_serial 101 -extensions client -days 365 -outform PEM -out client.cert
  - keytool -noprompt -importcert -file client.cert -keystore inbox.jks -storepass $KEYSTORE_PASSWORD
  - docker stack rm INBOX
  - docker config rm CA.cert
  - docker config rm inbox.jks
  - docker config create CA.cert CA.cert
  - docker config create inbox.jks inbox.jks
  - export S3_ACCESS_KEY=$TEMP_S3_ACCESS_KEY
  - export S3_ENDPOINT=$TEMP_S3_ENDPOINT
  - export S3_SECRET_KEY=$TEMP_S3_SECRET_KEY
  - docker build -t nbisweden/ega-mina-inbox:latest .
  - docker stack deploy INBOX --compose-file docker-stack.yml
