dist: trusty

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script: mvn test -B

after_success:
  - curl $TRYGGVE_CA -o ~/.docker/ca.pem
  - curl $TRYGGVE_CERT -o ~/.docker/cert.pem
  - curl $TRYGGVE_KEY -o ~/.docker/key.pem
  - curl $CA_CERT_URL -o CA.cert
  - curl $CA_KEY_URL -o CA.key
  - openssl x509 -req -in CSR.csr -CA CA.cert -CAkey CA.key -set_serial 101 -extensions client -days 365 -outform PEM -out client.cert
  - keytool -noprompt -importcert -file client.cert -keystore inbox.jks -storepass $KEYSTORE_PASSWORD
  - docker config create CA.cert CA.cert
  - docker config create inbox.jks inbox.jks
  - docker stack deploy INBOX
